FIREFLY_RKMEDIA_DEMO_VERSION = 1.0
FIREFLY_RKMEDIA_DEMO_SITE_METHOD = local
FIREFLY_RKMEDIA_DEMO_SITE = $(TOPDIR)/../app/firefly_rkmedia_demo
FIREFLY_RKMEDIA_DEMO_INSTALL_STAGING = YES 
FIREFLY_RKMEDIA_DEMO_INSTALL_TARGET = YES
FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += rkmedia zbar libcurl

ifeq ($(BR2_PACKAGE_OPENCV),y)
# The samples are using opencv instead of opencv3
FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += opencv
else ifeq ($(BR2_PACKAGE_OPENCV3),y)
FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += opencv3
else ifeq ($(BR2_PACKAGE_OPENCV4),y)
FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += opencv4
endif


FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += camera_engine_rkaiq
FIREFLY_RKMEDIA_DEMO_CONF_OPTS += -DUSE_RKAIQ=ON

FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += libdrm
FIREFLY_RKMEDIA_DEMO_CONF_OPTS += -DDRM_DISPLAY=ON

FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += linux-rga
FIREFLY_RKMEDIA_DEMO_CONF_OPTS += -DRKRGA=ON

FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += mpp
FIREFLY_RKMEDIA_DEMO_CONF_OPTS += -DRKMPP=ON \
        -DRKMPP_HEADER_DIR=$(STAGING_DIR)/usr/include/rockchip \
        -DRKMPP_LIB_NAME=rockchip_mpp

FIREFLY_RKMEDIA_DEMO_DEPENDENCIES += libv4l
FIREFLY_RKMEDIA_DEMO_CONF_OPTS += -DV4L2_CAPTURE=ON
$(eval $(cmake-package))
