#!/bin/sh

case "$1" in
	start)
		/usr/local/bin/adbd-daemon.sh start &
		;;
	stop)
		/usr/local/bin/adbd-daemon.sh stop
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
