FIREFLY_RKMEDIA_UVC_VERSION = 1.0
FIREFLY_RKMEDIA_UVC_SITE_METHOD = local
FIREFLY_RKMEDIA_UVC_SITE = $(TOPDIR)/../app/firefly_rkmedia_uvc/1126
FIREFLY_RKMEDIA_UVC_INSTALL_STAGING = YES 
FIREFLY_RKMEDIA_UVC_INSTALL_TARGET = YES
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += protobuf

FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DCOMPILES_FIREFLY_UVC_EXAMPLE=ON

FIREFLY_RKMEDIA_UVC_DEPENDENCIES += camera_engine_rkaiq
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DUSE_RKAIQ=ON

FIREFLY_RKMEDIA_UVC_DEPENDENCIES += libdrm
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DDRM_DISPLAY=ON

FIREFLY_RKMEDIA_UVC_DEPENDENCIES += linux-rga
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DRKRGA=ON

FIREFLY_RKMEDIA_UVC_DEPENDENCIES += mpp
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DRKMPP=ON \
        -DRKMPP_HEADER_DIR=$(STAGING_DIR)/usr/include/rockchip \
        -DRKMPP_LIB_NAME=rockchip_mpp

FIREFLY_RKMEDIA_UVC_DEPENDENCIES += libv4l
FIREFLY_RKMEDIA_UVC_CONF_OPTS += -DV4L2_CAPTURE=ON
FIREFLY_RKMEDIA_UVC_DEPENDENCIES += uvc_app rkmedia
$(eval $(cmake-package))
