################################################################################
#
# 
#
################################################################################

VISION_SERVICES_VERSION = 0.0.10
VISION_SERVICES_SITE = ssh://git@gitlab.hard-tech.org.ua/vision/vision-services.git
VISION_SERVICES_SITE_METHOD = git
VISION_SERVICES_INSTALL_STAGING = NO
VISION_SERVICES_INSTALL_TARGET = YES

VISION_SERVICES_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release

# all dependencies 
VISION_SERVICES_DEPENDENCIES = host-pkgconf syslog-ng rk_oem

# install to OEM dir
ifeq ($(BR2_PACKAGE_RK_OEM), y)
	VISION_SERVICES_TARGET_DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR)
	VISION_SERVICES_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
endif



ifeq ($(BR2_PACKAGE_VISION_AUTOPILOT_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_AUTOPILOT_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_AUTOPILOT_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_CAMERA_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_CAMERA_SERVICE=ON"
	VISION_SERVICES_DEPENDENCIES += rkmedia camera_engine_rkaiq libpng
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_CAMERA_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_DETECTION_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_DETECTION_SERVICE=ON"
	VISION_SERVICES_DEPENDENCIES += rknpu
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_DETECTION_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_TRACKER_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_TRACKER_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_TRACKER_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_DISPALY_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_DISPLAY_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_DISPLAY_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_MSP_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_MSP_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_MSP_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_QR_SCAN_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_QR_SCAN_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_QR_SCAN_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_VIDEO_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_VIDEO_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_VIDEO_SERVICE=OFF"
endif

ifeq ($(BR2_PACKAGE_VISION_OSD_SERVICE),y)
	VISION_SERVICES_CONF_OPTS += "-DBUILD_OSD_SERVICE=ON"
else
	VISION_SERVICES_CONF_OPTS += "-DBUILD_OSD_SERVICE=OFF"
endif


define VISION_SERVICES_INSTALL_CONFIG
	$(INSTALL) -D -m  644 $(@D)/assets/default_config.ini ${BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR}/etc/vision/config.ini  
endef

define VISION_SERVICES_INSTALL_ASSETS
	$(INSTALL) -D -m  644 $(@D)/assets/screensaver.png ${BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR}/assets/screensaver.png
endef

define VISION_SERVICES_INSTALL_SCRIPTS
	$(INSTALL) -D -m  755 $(@D)/assets/init.d/* "${TARGET_DIR}/etc/init.d/"
endef

define VISION_SERVICES_INSTALL_AI_MODEL
	$(INSTALL) -D -m  644 $(@D)/assets/default_model.rknn ${BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR}/ai_model/default_model.rknn
endef

VISION_SERVICES_POST_INSTALL_TARGET_HOOKS += VISION_SERVICES_INSTALL_CONFIG

VISION_SERVICES_POST_INSTALL_TARGET_HOOKS += VISION_SERVICES_INSTALL_ASSETS

VISION_SERVICES_POST_INSTALL_TARGET_HOOKS += VISION_SERVICES_INSTALL_SCRIPTS

VISION_SERVICES_POST_INSTALL_TARGET_HOOKS += VISION_SERVICES_INSTALL_AI_MODEL

$(eval $(cmake-package))
