XHLPR_APP_VERSION = 1.0
XHLPR_APP_SITE_METHOD = local
XHLPR_APP_SITE = $(TOPDIR)/../external/xhlpr_app
XHLPR_APP_INSTALL_STAGING = YES 
XHLPR_APP_INSTALL_TARGET = YES
XHLPR_APP_DEPENDENCIES += rkmedia libcurl libgdbus librkdb dbserver libIPCProtocol minilogger

ifeq ($(BR2_PACKAGE_OPENCV),y)
# The samples are using opencv instead of opencv3
XHLPR_APP_DEPENDENCIES += opencv
else ifeq ($(BR2_PACKAGE_OPENCV3),y)
XHLPR_APP_DEPENDENCIES += opencv3
else ifeq ($(BR2_PACKAGE_OPENCV4),y)
XHLPR_APP_DEPENDENCIES += opencv4
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_USE_AIQ), y)
XHLPR_APP_DEPENDENCIES += camera_engine_rkaiq
XHLPR_APP_CONF_OPTS += -DUSE_RKAIQ=ON
endif

ifeq ($(BR2_PACKAGE_DRM_DISPLAY_OUTPUT),y)
XHLPR_APP_DEPENDENCIES += libdrm
XHLPR_APP_CONF_OPTS += -DDRM_DISPLAY=ON
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_RKRGA),y)
XHLPR_APP_DEPENDENCIES += linux-rga
XHLPR_APP_CONF_OPTS += -DRKRGA=ON
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_MPP),y)
XHLPR_APP_DEPENDENCIES += mpp
XHLPR_APP_CONF_OPTS += -DRKMPP=ON \
        -DRKMPP_HEADER_DIR=$(STAGING_DIR)/usr/include/rockchip \
        -DRKMPP_LIB_NAME=rockchip_mpp
endif

ifeq ($(BR2_PACKAGE_RKMEDIA_V4L2_CAPTURE),y)
ifeq ($(BR2_PACKAGE_LIBV4L2),y)
XHLPR_APP_DEPENDENCIES += libv4l
endif
XHLPR_APP_CONF_OPTS += -DV4L2_CAPTURE=ON
endif

ifeq ($(BR2_PACKAGE_NETSERVER_SANITIZER_DYNAMIC), y)
XHLPR_APP_CONF_CONF_OPTS += -DSANITIZER_DYNAMIC=ON
else

ifeq ($(BR2_PACKAGE_NETSERVER_SANITIZER_STATIC), y)
XHLPR_APP_CONF_CONF_OPTS += -DSANITIZER_STATIC=ON
endif
endif

$(eval $(cmake-package))
