name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ ubuntu-20.04, self-hosted ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: ./build
        
    - name: Install depends
      run: |
        sudo apt update
        sudo apt-get install -y expect-dev python2 git git-lfs expect-dev debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git device-tree-compiler
    
    - name: build U-boot
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh uboot
        
    - name: build Kernel
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh kernel

    - name: build rtl8812au
      working-directory: ./build/rtl8812au
      run: |
        make -j4
        make install
  
    - name: build rootfs
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh rootfs
        
    - name: Make Firmware
      working-directory: ./build
      run: bash mkfirmware.sh


    - name: Upload Build-log
      uses: actions/upload-artifact@v3
      if: always()
      with: 
       name: build.log
       path: ./build/br.log

    - name: Upload SDK from GitHub Action
      uses: actions/upload-artifact@v3
      with: 
       name: artifacts
       path: ./build/rockdev

