name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: ./build
        
    - name: Install depends
      run: |
        sudo apt update
        sudo apt-get install -y expect-dev python2 git git-lfs expect-dev debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git device-tree-compiler
    
    - name: check dir
      working-directory: ./build
      run: |
        ls -l
        pwd
    - name: check dir
      working-directory: ./build
      run: |
        ls -l
        sleep 1
        cat device/rockchip/common/build.sh
    
    - name: build U-boot
      run: |
        bash device/rockchip/common/build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash device/rockchip/common/build.sh uboot

