name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: ./build
        
    # - name: Install depends
    #  run: |
    #    sudo apt update
    #    sudo apt-get install -y bison texinfo flex cmake libssl-dev liblz4-tool patchelf chrpath gawk expect-dev python2 git git-lfs expect-dev debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git device-tree-compiler
    
    - name: build U-boot
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh uboot
        
    - name: build Kernel
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh kernel

    - name: make Kernel headers
      working-directory: ./build
      run: |
        cd kernel
        make ARCH=arm rv1126_vision_defconfig
        make ARCH=arm INSTALL_HDR_PATH=../kernel_headers headers_install 

    - name: build rtl8812au
      working-directory: ./build/rtl8812au
      run: |
        make -j4
        make install
  
    - name: build buildroot
      working-directory: ./build
      run: |
        source envsetup.sh rockchip_rv1126_vision
        cd buildroot
        make clean
        cd ..
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash build.sh rootfs
        
    - name: Make Firmware
      working-directory: ./build
      run: |
        bash build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
        bash mkfirmware.sh

    - name: Upload Build-log
      uses: actions/upload-artifact@v3
      if: always()
      with: 
       name: build.log
       path: ./build/br.log

    - name: Upload Firmware from GitHub Action
      uses: actions/upload-artifact@v3
      with: 
       name: firmware
       path: ./build/rockdev

    - name: Upload SDK from GitHub Action
      uses: actions/upload-artifact@v3
      with: 
       name: SDK
       path: ./build/rockdev_sdk/vision-sdk.tar.gz

    - name: Upload Kernel headers from GitHub Action
      uses: actions/upload-artifact@v3
      with: 
       name: kernel headers
       path: ./build/kernel_headers   
