name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install depends
      run: |
        sudo apt update
        sudo apt-get install -y expect-dev python2 git git-lfs expect-dev debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git device-tree-compiler
    
    - name: check dir
      run: |
        ls -l
        pwd
    - name: check dir
      run: cat build.sh 
    
#     - name: build U-boot
#       run: |
#         bash vision-rv1126/build.sh device/rockchip/rv1126_rv1109/vision-rv1126.mk
#         bash vision-rv1126/build.sh uboot

